MODE_QUESTIONS: dict[str, list[str]] = {
    "general": [
        "¿Quién es el mejor jugador de la historia y por qué?",
        "¿Qué equipo ha sido el más dominante en una temporada?",
        "¿Cuál fue el mejor partido de la historia del fútbol?",
        "Analiza la evolución táctica del fútbol en los últimos 30 años",
        "¿Quién ganará el próximo Mundial?",
    ],
    "scout": [
        "Analiza a Lamine Yamal como proyecto de futuro",
        "Scout report: Jude Bellingham vs Pedri",
        "¿Quiénes son las 5 mayores promesas del fútbol mundial?",
        "Analiza a Endrick y su potencial en el Real Madrid",
        "Busca jugadores infravalorados en la Serie A",
    ],
    "tactical": [
        "Analiza el 4-3-3 de Guardiola vs el 4-4-2 de Simeone",
        "¿Cómo ha evolucionado la posición de falso 9?",
        "Explica el pressing de Klopp vs la defensa baja de Mourinho",
        "¿Qué es un 'box midfield' y cómo funciona?",
        "Analiza la salida de balón del FC Barcelona 2024-25",
    ],
    "sporting_director": [
        "Diagnóstico deportivo del Manchester United 2025",
        "¿Qué necesita el FC Barcelona para volver a ganar la Champions?",
        "Evalúa la planificación deportiva del Real Madrid",
        "¿Cómo debe construir un proyecto un equipo recién ascendido?",
        "Análisis de la cantera del Ajax vs La Masia",
    ],
    "transfer_market": [
        "¿Qué fichajes necesita el Real Madrid para 2025-26?",
        "Top 10 jugadores más valiosos del mundo actualmente",
        "¿Quién debería ser el reemplazo de Lewandowski en el Barça?",
        "Agentes libres top para 2025",
        "Jóvenes talentos por menos de 20M",
    ],
    "journalist": [
        "Escribe una crónica de la final de Champions 2024",
        "Reportaje: El impacto de la Eurocopa 2024 en el fútbol europeo",
        "Columna de opinión: ¿El VAR mejora o empeora el fútbol?",
        "Entrevista ficticia a Johan Cruyff",
        "Previa del próximo Clásico Real Madrid vs Barcelona",
    ],
    "statistician": [
        "Compara las estadísticas de Messi y Ronaldo en su prime",
        "Explica qué es el xG con ejemplos de la Premier League",
        "Los 10 récords más impresionantes del fútbol",
        "Analiza las métricas de Rodri en la 2023-24",
        "¿Qué equipo tiene la mejor eficiencia goleadora de Europa?",
    ],
    "goat": [
        "Messi vs Maradona: ¿quién fue mejor?",
        "Cristiano Ronaldo vs Pelé: debate generacional",
        "Los 5 mejores entrenadores de la historia",
        "¿Quién es el mejor centrocampista de la historia?",
        "Top 10 defensas de todos los tiempos",
    ],
    "encyclopedia": [
        "Lista completa de todos los campeones del Mundo",
        "¿Quiénes han ganado más Balones de Oro?",
        "Máximos goleadores históricos del fútbol",
        "Todos los campeones de la Champions League por año",
        "Récords imbatibles del fútbol mundial",
    ],
    "content_creator": [
        "Crea un hilo de X sobre la historia del 4-3-3",
        "Guión para un video de 10 min sobre el fútbol total",
        "Post de LinkedIn: lecciones de liderazgo del fútbol",
        "Newsletter semanal: lo mejor de la jornada europea",
        "Guión para un short sobre el mejor gol de la historia",
    ],
    "coach": [
        "Diseña una sesión de entrenamiento de posesión para juveniles",
        "Microciclo semanal para un equipo profesional",
        "Ejercicios para mejorar la salida de balón bajo presión",
        "Planificación de pretemporada para fútbol base",
        "Cómo entrenar la presión post-pérdida",
    ],
    "talent_detector": [
        "Joyas ocultas del fútbol sudamericano",
        "Promesas africanas que llegarán a Europa pronto",
        "Talento emergente en la Liga Portuguesa",
        "¿Qué jugadores sub-20 serán estrellas mundiales en 2030?",
        "Mercados emergentes: talento en la MLS y Asia",
    ],
}
